import webpush from 'web-push';
import type { ForemanConfig } from '../config/index.js';
import { optionalSecret } from '../secrets/index.js';
import { addSubscription, getJob, listSubscriptions, removeSubscription, type PushSub } from '../db/index.js';
import { bus } from '../bus.js';
import { createLogger } from '../logger.js';

const log = createLogger('push');

/**
 * Web Push (VAPID) to the installed PWA, plus an optional ntfy publisher (PRD FR4/FR5).
 * Escalations and completions arrive as native phone notifications. Keys are generated by
 * `foreman init`; without them, push is simply disabled.
 */
class PushService {
  private enabled = false;
  private publicKey = '';
  private ntfyTopic?: string;

  init(_config: ForemanConfig): void {
    const pub = optionalSecret('VAPID_PUBLIC_KEY');
    const priv = optionalSecret('VAPID_PRIVATE_KEY');
    this.ntfyTopic = optionalSecret('FOREMAN_NTFY_TOPIC');
    if (pub && priv) {
      webpush.setVapidDetails('mailto:foreman@localhost', pub, priv);
      this.publicKey = pub;
      this.enabled = true;
      log.info('Web Push enabled');
    } else {
      log.info('Web Push disabled (run `foreman init` to generate VAPID keys)');
    }
    this.subscribeToBus();
  }

  vapidPublicKey(): string {
    return this.publicKey;
  }

  subscribe(sub: PushSub): void {
    addSubscription(sub);
  }
  unsubscribe(endpoint: string): void {
    removeSubscription(endpoint);
  }

  /** Notify on new escalations and on terminal job states. */
  private subscribeToBus(): void {
    bus.on('event', (e: { type: string; jobId: string; message: string; data?: Record<string, unknown> }) => {
      // A fresh escalation (has an id, not yet a decision) → "needs you".
      if (e.type === 'escalation' && e.data?.id && !('decision' in (e.data ?? {}))) {
        const job = getJob(e.jobId);
        void this.send({
          title: `${job?.name ?? e.jobId} needs you`,
          body: e.message,
          tag: String(e.data.id),
          url: `/#/jobs/${e.jobId}`,
        });
      }
      // Completion / failure.
      if (e.type === 'state' && (e.message === 'done' || e.message === 'failed')) {
        const job = getJob(e.jobId);
        void this.send({
          title: `${job?.name ?? e.jobId} ${e.message}`,
          body: job?.lastActivity ?? '',
          tag: `${e.jobId}-${e.message}`,
          url: `/#/jobs/${e.jobId}`,
        });
      }
    });
  }

  async send(payload: { title: string; body: string; tag?: string; url?: string }): Promise<void> {
    // ntfy: a simple dumb-pipe notifier, independent of Web Push.
    if (this.ntfyTopic) {
      void fetch(`https://ntfy.sh/${this.ntfyTopic}`, {
        method: 'POST',
        body: `${payload.title}\n${payload.body}`,
      }).catch(() => {});
    }
    if (!this.enabled) return;
    const data = JSON.stringify(payload);
    for (const sub of listSubscriptions()) {
      try {
        await webpush.sendNotification(sub, data);
      } catch (err) {
        const status = (err as { statusCode?: number }).statusCode;
        if (status === 404 || status === 410) {
          removeSubscription(sub.endpoint); // subscription expired
        } else {
          log.warn(`push send failed: ${(err as Error).message}`);
        }
      }
    }
  }
}

export const push = new PushService();
