import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import webpush from 'web-push';
import { findConfigPath } from '../config/index.js';
import { setSecret, resolveSecret } from '../secrets/index.js';
import { isKeychainAvailable } from '../secrets/keychain.js';

/**
 * `foreman init` provisioning (PRD FR9 / DESIGN §2). Mints the Gemini API key in the
 * operator's GCP project, stores all secrets in the Keychain (or guides toward .env), and
 * writes a LiteLLM proxy config mapping the Director/Router roles to live model IDs.
 */

export const DIRECTOR_MODEL = 'gemini-3.5-flash';
export const ROUTER_MODEL = 'gemini-3.1-flash-lite';

function run(cmd: string, args: string[]): { ok: boolean; stdout: string; stderr: string } {
  const r = spawnSync(cmd, args, { encoding: 'utf8' });
  return { ok: r.status === 0, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

/**
 * Resolve the GCP project to mint the Gemini key in — no hardcoded project (publish-clean).
 * Precedence: explicit --project → FOREMAN_GCP_PROJECT → gcloud's active project.
 */
export function resolveGcpProject(explicit?: string): string {
  if (explicit) return explicit;
  if (process.env.FOREMAN_GCP_PROJECT) return process.env.FOREMAN_GCP_PROJECT;
  const active = run('gcloud', ['config', 'get-value', 'project']).stdout.trim();
  if (active && active !== '(unset)') return active;
  throw new Error(
    'No GCP project. Pass --project <id>, set FOREMAN_GCP_PROJECT, or run `gcloud config set project <id>`.',
  );
}

export function hasGcloud(): boolean {
  return run('gcloud', ['--version']).ok;
}

/** Enable the Gemini + API Keys services on the project (idempotent). */
export function enableServices(project: string): void {
  const r = run('gcloud', [
    'services',
    'enable',
    'generativelanguage.googleapis.com',
    'apikeys.googleapis.com',
    `--project=${project}`,
  ]);
  if (!r.ok) throw new Error(`gcloud services enable failed: ${r.stderr.trim()}`);
}

/** Create (or reuse) a restricted Gemini API key and return its key string. */
export function provisionGeminiKey(project: string): string {
  // Reuse if a foreman-gemini key already exists, so re-running init is safe.
  const list = run('gcloud', [
    'services',
    'api-keys',
    'list',
    `--project=${project}`,
    '--filter=displayName=foreman-gemini',
    '--format=value(name)',
  ]);
  const existing = list.stdout.trim().split('\n').filter(Boolean)[0];
  if (existing) {
    const ks = run('gcloud', [
      'services',
      'api-keys',
      'get-key-string',
      existing,
      '--format=value(keyString)',
    ]);
    if (ks.ok && ks.stdout.trim()) return ks.stdout.trim();
  }
  const create = run('gcloud', [
    'services',
    'api-keys',
    'create',
    `--project=${project}`,
    '--display-name=foreman-gemini',
    '--api-target=service=generativelanguage.googleapis.com',
    '--format=value(response.keyString)',
  ]);
  if (!create.ok || !create.stdout.trim()) {
    throw new Error(`gcloud api-keys create failed: ${create.stderr.trim()}`);
  }
  return create.stdout.trim();
}

/** Verify a model id actually answers on the Gemini API; returns the working id or null. */
export async function verifyGeminiModel(key: string, model: string): Promise<boolean> {
  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}?key=${key}`,
    );
    return res.ok;
  } catch {
    return false;
  }
}

export function writeLiteLLMConfig(opts: {
  director: string;
  router: string;
  repoRoot: string;
}): string {
  const cfg = `# Generated by \`foreman init\`. Start the proxy with:
#   litellm --config litellm.config.yaml
# It reads GEMINI_API_KEY from the environment (export it or source your .env).
model_list:
  - model_name: director
    litellm_params:
      model: gemini/${opts.director}
      api_key: os.environ/GEMINI_API_KEY
  - model_name: router
    litellm_params:
      model: gemini/${opts.router}
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_KEY
`;
  const out = path.join(opts.repoRoot, 'litellm.config.yaml');
  fs.writeFileSync(out, cfg);
  return out;
}

export function randomToken(bytes = 32): string {
  return crypto.randomBytes(bytes).toString('base64url');
}

/** Merge keys into the repo-root .env (create if missing, update in place), 0600. */
function upsertEnv(repoRoot: string, vars: Record<string, string>): string {
  const envPath = path.join(repoRoot, '.env');
  const lines = fs.existsSync(envPath)
    ? fs.readFileSync(envPath, 'utf8').replace(/\n+$/, '').split('\n')
    : [];
  for (const [k, v] of Object.entries(vars)) {
    const line = `${k}=${v}`;
    const idx = lines.findIndex((l) => l.startsWith(`${k}=`));
    if (idx >= 0) lines[idx] = line;
    else lines.push(line);
  }
  fs.writeFileSync(envPath, lines.join('\n') + '\n', { mode: 0o600 });
  return envPath;
}

export interface InitResult {
  geminiKeySource: 'provisioned' | 'existing' | 'provided';
  directorModel: string;
  routerModel: string;
  litellmConfigPath: string;
  storedTo: 'keychain' | 'env';
  /** Where secrets were written when not using the Keychain. */
  envPath?: string;
  keyReachable: boolean;
  notes: string[];
}

/**
 * Provision FOREMAN. Two paths:
 *   • `geminiKey` given → use it directly (e.g. a free key from Google AI Studio); no gcloud.
 *   • otherwise → mint a restricted key in the GCP project via gcloud.
 * Either way: generate the dashboard/proxy/VAPID secrets, store them (Keychain on macOS, else
 * written straight into .env — never echoed), and write litellm.config.yaml.
 */
export async function runInit(opts: { project?: string; geminiKey?: string }): Promise<InitResult> {
  const notes: string[] = [];
  const repoRoot = path.dirname(findConfigPath() ?? path.join(process.cwd(), 'foreman.yaml'));

  // 1. Gemini key — direct (AI Studio) or minted via gcloud.
  let geminiKey: string;
  let geminiKeySource: InitResult['geminiKeySource'];
  if (opts.geminiKey?.trim()) {
    geminiKey = opts.geminiKey.trim();
    geminiKeySource = 'provided';
  } else {
    if (!hasGcloud()) {
      throw new Error(
        'gcloud CLI not found on PATH. Either install the Google Cloud SDK, or skip it entirely ' +
          'with a free key:\n  foreman init --gemini-key <KEY>   (get one at https://aistudio.google.com/apikey)',
      );
    }
    const project = resolveGcpProject(opts.project);
    const alreadyHadKey = !!resolveSecret('GEMINI_API_KEY');
    enableServices(project);
    geminiKey = provisionGeminiKey(project);
    geminiKeySource = alreadyHadKey ? 'existing' : 'provisioned';
  }

  // 2. Secrets → Keychain (macOS) or straight into .env (everyone else).
  const storedTo: 'keychain' | 'env' = isKeychainAvailable() ? 'keychain' : 'env';
  const vapid = webpush.generateVAPIDKeys(); // Web Push keypair (M4) — generated once, reused.
  let envPath: string | undefined;
  if (storedTo === 'keychain') {
    setSecret('GEMINI_API_KEY', geminiKey);
    if (!resolveSecret('LITELLM_KEY')) setSecret('LITELLM_KEY', randomToken());
    if (!resolveSecret('FOREMAN_TOKEN')) setSecret('FOREMAN_TOKEN', randomToken());
    if (!resolveSecret('VAPID_PUBLIC_KEY')) {
      setSecret('VAPID_PUBLIC_KEY', vapid.publicKey);
      setSecret('VAPID_PRIVATE_KEY', vapid.privateKey);
    }
  } else {
    // Write directly to .env so nothing sensitive is printed to the terminal/scrollback.
    envPath = upsertEnv(repoRoot, {
      GEMINI_API_KEY: geminiKey,
      LITELLM_KEY: resolveSecret('LITELLM_KEY')?.value ?? randomToken(),
      FOREMAN_TOKEN: resolveSecret('FOREMAN_TOKEN')?.value ?? randomToken(),
      VAPID_PUBLIC_KEY: resolveSecret('VAPID_PUBLIC_KEY')?.value ?? vapid.publicKey,
      VAPID_PRIVATE_KEY: resolveSecret('VAPID_PRIVATE_KEY')?.value ?? vapid.privateKey,
    });
  }

  // 3. Verify model ids against the live API, falling back to the *-latest aliases.
  let director = DIRECTOR_MODEL;
  let router = ROUTER_MODEL;
  const dOk = await verifyGeminiModel(geminiKey, director);
  if (!dOk) {
    notes.push(`Model "${director}" did not resolve; falling back to gemini-flash-latest.`);
    director = 'gemini-flash-latest';
  }
  const rOk = await verifyGeminiModel(geminiKey, router);
  if (!rOk) {
    notes.push(`Model "${router}" did not resolve; falling back to gemini-flash-lite-latest.`);
    router = 'gemini-flash-lite-latest';
  }
  // If the key can't reach Gemini at all, the fallbacks won't help — flag it loudly.
  const keyReachable = dOk || rOk || (await verifyGeminiModel(geminiKey, 'gemini-flash-latest'));
  if (!keyReachable) {
    notes.push('⚠ Could not reach Gemini with this key — double-check it (and that the API is enabled).');
  }

  // 4. LiteLLM config
  const litellmConfigPath = writeLiteLLMConfig({ director, router, repoRoot });

  return {
    geminiKeySource,
    directorModel: director,
    routerModel: router,
    litellmConfigPath,
    storedTo,
    ...(envPath ? { envPath } : {}),
    keyReachable,
    notes,
  };
}
