import { spawnSync } from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import webpush from 'web-push';
import { findConfigPath } from '../config/index.js';
import { setSecret, resolveSecret } from '../secrets/index.js';
import { isKeychainAvailable } from '../secrets/keychain.js';

/**
 * `foreman init` provisioning (PRD FR9 / DESIGN §2). Mints the Gemini API key in the
 * operator's GCP project, stores all secrets in the Keychain (or guides toward .env), and
 * writes a LiteLLM proxy config mapping the Director/Router roles to live model IDs.
 */

export const DIRECTOR_MODEL = 'gemini-3.5-flash';
export const ROUTER_MODEL = 'gemini-3.1-flash-lite';

function run(cmd: string, args: string[]): { ok: boolean; stdout: string; stderr: string } {
  const r = spawnSync(cmd, args, { encoding: 'utf8' });
  return { ok: r.status === 0, stdout: r.stdout ?? '', stderr: r.stderr ?? '' };
}

/**
 * Resolve the GCP project to mint the Gemini key in — no hardcoded project (publish-clean).
 * Precedence: explicit --project → FOREMAN_GCP_PROJECT → gcloud's active project.
 */
export function resolveGcpProject(explicit?: string): string {
  if (explicit) return explicit;
  if (process.env.FOREMAN_GCP_PROJECT) return process.env.FOREMAN_GCP_PROJECT;
  const active = run('gcloud', ['config', 'get-value', 'project']).stdout.trim();
  if (active && active !== '(unset)') return active;
  throw new Error(
    'No GCP project. Pass --project <id>, set FOREMAN_GCP_PROJECT, or run `gcloud config set project <id>`.',
  );
}

export function hasGcloud(): boolean {
  return run('gcloud', ['--version']).ok;
}

/** Enable the Gemini + API Keys services on the project (idempotent). */
export function enableServices(project: string): void {
  const r = run('gcloud', [
    'services',
    'enable',
    'generativelanguage.googleapis.com',
    'apikeys.googleapis.com',
    `--project=${project}`,
  ]);
  if (!r.ok) throw new Error(`gcloud services enable failed: ${r.stderr.trim()}`);
}

/** Create (or reuse) a restricted Gemini API key and return its key string. */
export function provisionGeminiKey(project: string): string {
  // Reuse if a foreman-gemini key already exists, so re-running init is safe.
  const list = run('gcloud', [
    'services',
    'api-keys',
    'list',
    `--project=${project}`,
    '--filter=displayName=foreman-gemini',
    '--format=value(name)',
  ]);
  const existing = list.stdout.trim().split('\n').filter(Boolean)[0];
  if (existing) {
    const ks = run('gcloud', [
      'services',
      'api-keys',
      'get-key-string',
      existing,
      '--format=value(keyString)',
    ]);
    if (ks.ok && ks.stdout.trim()) return ks.stdout.trim();
  }
  const create = run('gcloud', [
    'services',
    'api-keys',
    'create',
    `--project=${project}`,
    '--display-name=foreman-gemini',
    '--api-target=service=generativelanguage.googleapis.com',
    '--format=value(response.keyString)',
  ]);
  if (!create.ok || !create.stdout.trim()) {
    throw new Error(`gcloud api-keys create failed: ${create.stderr.trim()}`);
  }
  return create.stdout.trim();
}

/** Verify a model id actually answers on the Gemini API; returns the working id or null. */
export async function verifyGeminiModel(key: string, model: string): Promise<boolean> {
  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${model}?key=${key}`,
    );
    return res.ok;
  } catch {
    return false;
  }
}

export function writeLiteLLMConfig(opts: {
  director: string;
  router: string;
  repoRoot: string;
}): string {
  const cfg = `# Generated by \`foreman init\`. Start the proxy with:
#   litellm --config litellm.config.yaml
# It reads GEMINI_API_KEY from the environment (export it or source your .env).
model_list:
  - model_name: director
    litellm_params:
      model: gemini/${opts.director}
      api_key: os.environ/GEMINI_API_KEY
  - model_name: router
    litellm_params:
      model: gemini/${opts.router}
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_KEY
`;
  const out = path.join(opts.repoRoot, 'litellm.config.yaml');
  fs.writeFileSync(out, cfg);
  return out;
}

export function randomToken(bytes = 32): string {
  return crypto.randomBytes(bytes).toString('base64url');
}

export interface InitResult {
  geminiKeySource: 'provisioned' | 'existing';
  directorModel: string;
  routerModel: string;
  litellmConfigPath: string;
  storedTo: 'keychain' | 'env';
  notes: string[];
}

export async function runInit(opts: { project: string }): Promise<InitResult> {
  const notes: string[] = [];
  const repoRoot = path.dirname(findConfigPath() ?? path.join(process.cwd(), 'foreman.yaml'));

  if (!hasGcloud()) {
    throw new Error('gcloud CLI not found on PATH. Install the Google Cloud SDK first.');
  }

  // 1. Gemini key (reuse if present)
  const alreadyHadKey = !!resolveSecret('GEMINI_API_KEY');
  enableServices(opts.project);
  const geminiKey = provisionGeminiKey(opts.project);

  // 2. Secrets → keychain (or guide to .env)
  const storedTo: 'keychain' | 'env' = isKeychainAvailable() ? 'keychain' : 'env';
  // Web Push VAPID keypair (M4) — generated once, reused on re-run.
  const vapid = webpush.generateVAPIDKeys();
  if (storedTo === 'keychain') {
    setSecret('GEMINI_API_KEY', geminiKey);
    if (!resolveSecret('LITELLM_KEY')) setSecret('LITELLM_KEY', randomToken());
    if (!resolveSecret('FOREMAN_TOKEN')) setSecret('FOREMAN_TOKEN', randomToken());
    if (!resolveSecret('VAPID_PUBLIC_KEY')) {
      setSecret('VAPID_PUBLIC_KEY', vapid.publicKey);
      setSecret('VAPID_PRIVATE_KEY', vapid.privateKey);
    }
  } else {
    notes.push(
      'Non-macOS: add these to your .env — ' +
        `GEMINI_API_KEY=${geminiKey}  LITELLM_KEY=${randomToken()}  FOREMAN_TOKEN=${randomToken()}  ` +
        `VAPID_PUBLIC_KEY=${vapid.publicKey}  VAPID_PRIVATE_KEY=${vapid.privateKey}`,
    );
  }

  // 3. Verify model ids, fall back to the *-latest aliases if a name doesn't resolve.
  let director = DIRECTOR_MODEL;
  let router = ROUTER_MODEL;
  if (!(await verifyGeminiModel(geminiKey, director))) {
    notes.push(`Model "${director}" did not resolve; falling back to gemini-flash-latest.`);
    director = 'gemini-flash-latest';
  }
  if (!(await verifyGeminiModel(geminiKey, router))) {
    notes.push(`Model "${router}" did not resolve; falling back to gemini-flash-lite-latest.`);
    router = 'gemini-flash-lite-latest';
  }

  // 4. LiteLLM config
  const litellmConfigPath = writeLiteLLMConfig({ director, router, repoRoot });

  return {
    geminiKeySource: alreadyHadKey ? 'existing' : 'provisioned',
    directorModel: director,
    routerModel: router,
    litellmConfigPath,
    storedTo,
    notes,
  };
}
